middleware:
  index:
    onStartup: true
  allowed-origins:
  - http://middleware:9000

spring:
  data:
    rest:
      # CAUTION: leaving this on will permit all requests from localhost, breaks various UI requests and SSR
      authorize-hal-browser: true
    solr:
      host: http://solr:8983/solr
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
  profiles:
    active: dev

# NOTE: purpose in this context is to make profile images visible 
vivo:
  base-url: https://vstf-vivo.cloud.duke.edu   
