middleware:
  index:
    onStartup: true

spring:
  data:
    rest:
      # CAUTION: leaving this on will permit all requests from localhost, breaks various UI requests and SSR
      authorize-hal-browser: true
    solr:
      host: http://solr:8983/solr
      #host: http://127.0.0.1:8988/solr
      #host: https://scholars-discovery-solr-scholars.cloud.duke.edu/solr
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
  profiles:
    active: dev
